### ISSUE TITLE
cortextstore.splice not working as expected

### ISSUE THREAD

**Issue by serle** [mquan/cortex#100]
I find that the following is emptying the array completely:

                cortexstore.splice(index, 1);

whereas the following works:

                let temp = cortexstore.val();
                temp.splice(index, 1);
                cortexstore.set(temp);

**Comment by mquan** [comment]
Since cortex 2.0, we're moving toward immutable data, meaning we don't mutate the current wrapper. The following code shows `splice` working fine.

```javascript
var data = [1, 2, 3, 4, 5];
var newCortex;
var cortex = new Cortex(data, function(updated) {
  newCortex = updated;
});

cortex.splice(2, 1);

// now the new value is set in newCortex
newCortex.val();  // => [1, 2, 4, 5]
```

The second part of your code works because you get the reference to the value and mutate it so it works even without calling `cortexstore.set(temp)`.

Please note that in cortex 2.0, you have to access the updated cortex in the callback to get the new value. Please check out the examples.
