### ISSUE TITLE
Why not use Immutable.js?

### ISSUE THREAD

**Issue by ccorcos** [mquan/cortex#102]
I believe they implement cursors as well

**Comment by mquan** [comment]
I originally planned to do this but 1. Immutable.js is kinda heavy, it has a ton of features that cortex does not need and 2. we still have to do most of the work to support deeply nested structure, which is the main goal of cortex. So I decided against including it as a dependency.

**Comment by ccorcos** [comment]
> 2. we still have to do most of the work to support deeply nested structure, which is the main goal of cortex.

What do you mean by this? Nested cursors?

**Comment by mquan** [comment]
Immutable.js wraps your data. Now if cortex wraps the Immutable wrapper then in order to access/update the data cortex must wrap and unwrap the Immutable wrappers. This is way more work than actually implementing our own immutable structure. This shows in the resulting code, cortex supports immutable data with only 4.5kb after minified and gzipped.

Is there any feature in Immutable.js that you'd like to see in cortex?

**Comment by ccorcos** [comment]
Hmm. I'm not entirely sure how cortex works -- I just know that immutable.js is really efficient at sharing datastructures. Does cortex do the same?

**Comment by mquan** [comment]
> really efficient at sharing datastructures

What do you mean by this? Cortex only creates a new branch when a node in that branch changes, it retains the rest of the tree nodes if nothing else changes. Cortex also batches updates together so multiple changes only results in one React render. You can get more info from the README

**Comment by ccorcos** [comment]
I'm talking about this stuff from quoted from https://facebook.github.io/immutable-js/:

> They are highly efficient on modern JavaScript VMs by using structural sharing via hash maps tries and vector tries as popularized by Clojure and Scala, minimizing the need to copy or cache data.
