### ISSUE TITLE
Integration with shouldComponentUpdate

### ISSUE THREAD

**Issue by pixelcort** [mquan/cortex#2]
Since Cortex is managing state there's probably a best way to integrate with React's `shouldComponentUpdate` method: http://facebook.github.io/react/docs/component-specs.html#updating-shouldcomponentupdate

Any ideas where to start?

**Comment by jhorman** [comment]
I am not sure this addresses the concern about how to properly integrate with shouldComponentUpdate. In the examples of cortex that I see, if any node in the cortex tree changes, setProps at the top will tell react to re-render everything. Every react component will re-render. https://github.com/omniscientjs/omniscient makes a point to implement shouldComponentUpdate in a way that prevents re-renders.

The README says

> You SHOULD NOT use getChanges and didChange to implement shouldComponentUpdate unless your components ONLY rely on cortex object to rerender

Is this just saying that `didChange` is ok as long as I and (&&) it together with other checks I might have?

**Comment by mquan** [comment]
> Is this just saying that didChange is ok as long as I and (&&) it together with other checks I might have?

Not really, let's say you use cortex as props and your `shouldComponentUpdate` check for changes with `this.props.cortex.didChange() && validChange(this.state.someState)`. When your props cortex first changes, the function will return true. But the next time when your state changes it will also return true because the changes in props is persisted. What we really need is making every cortex node immutable.

**Comment by jhorman** [comment]
Ah. Ok. I see. Yeah. Unfortunate. I wonder if one could set an unused property to clear the relevant changes. Not sure exactly where in react that could happen. Ideally after the re-render was completely finished.
