### ISSUE TITLE
changing one key of the object changes the entire object

### ISSUE THREAD

**Issue by panbhag** [mquan/cortex#77]
This issue defeats the purpose of this library. my entire react application re-renders every time any data changes. For example take the skyline example(https://mquan.github.io/cortex/examples/skyline/) and for every components render function(in application.js), add a console.log('rendering <component name>..'). Then when you run the example and just toggle the state of any of the light by clicking on it, you will note that all the components render function is called. To take advantage of immutability only the render functions of parts which have changed should have been called. Else there is no difference of using plain data vs immutable data. The same can be achieved using normal json data and re rendering the entire app on any data change.

var data = new Cortex({a:1,b:2});
var oa = data.a;
var ob = data.b;
data.b.set(10); 
oa == data.a 
// as a has not changed this should not change, but this is returning false

**Comment by panbhag** [comment]
Just realised, that it no where mentions that it follows immutable. so closing it.

**Comment by mquan** [comment]
Because something in the subtree changes cortex will rewrap at the level above the changes. You're right that it should be smarter and keep the wrappers that didn't change. However, this isn't trivial for array insertion and deletion so I initially chose to implement this way. I'm investigating ways to make rewrapping more efficient. Thanks

**Comment by mquan** [comment]
cortex 2.0.0 fixes this issue with immutable data
