### ISSUE TITLE
Please explain this part 

### ISSUE THREAD

**Issue by idibidiart** [mquan/cortex#99]
"uses immutable data, which allows fast comparison in shouldComponentUpdate"

but Cortex also does "deep comparison" to see if it should generate the new immutable reference, right? Or did I misunderstand?

However, I imagine immutability is desired regardless of wether the props changed or not (so that multiple components referencing the same data structure could getValue and mutate it locally without mutating that data structure) 

Another question, once again born of my ignorance, is why do deep comparison? is the wrapping process expensive while deep comparison of necessarily shallow structures is less expensive? Wouldn't it be a good idea to limit the depth of structures given to .set() to be just 1 or 2 levels deep and accessing deeply nested structures directly?

Please enlighten.

**Comment by mquan** [comment]
1. Immutability means that for a given node once it's created its data does not change. But that doesn't mean your data can't be updated. You simply create a new node and point the reference to the new node instead of old one. Consider this example

```
      A
    /     \
  B      C
```

Now let's say we want to update data in B, instead of changing it directly we simply create a new node B' with the new data and attach it to the tree. We also need to create a new node A' because A contains B, so when B changes A must also change. So we get a new data tree like this

```
   A'
 /    \
B'    C
```

The old data tree actually still exists until nothing references it and it gets garbage collected. Because B' is a different object than B, we can simply compare `B !== B'` 

2. Cortex uses deep comparison to make sure that we don't create a new node when there's no data change. Note that deep comparison is not done at the root, it's performed at the level you call `set`. So for instance, if you call `a.b.c.d.e.set('foo')` the comparison is only between value of e and 'foo'. But if you call `a.set({b: {c: {d: {e: 'foo'}}}})` then it'd be more costly.

The reason we don't force shallow update is because it makes sense to have deep update sometimes. Imagine a multiplayer game that has many nested game states and requires constant updates from other player. It makes sense to simply apply the entire game state and let cortex figure out which nodes changed. Otherwise, you have to implement a bunch of custom events for each type of game state changes.

Plus deep comparison is only done once. If you blindly update without comparing and not using immutability then you have to perform deep comparison in every component that you want to properly implement `shouldComponentUpdate`

Hope this clears things up.
